### ISSUE TITLE
erro no working

### ISSUE THREAD

**Issue by Blue2322** [NewBeginning6/Subdir-vul-find#1]
java.lang.Exception: Extension class is not a recognized type
	at burp.u2_.J(Unknown Source)
	at burp.u2_.<init>(Unknown Source)
	at burp.q8e.f(Unknown Source)
	at burp.tze.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by NewBeginning6** [comment]
This is not a burp plugin
